# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.8)
   message(FATAL_ERROR "CMake >= 2.8.0 required")
endif()
if(CMAKE_VERSION VERSION_LESS "2.8.3")
   message(FATAL_ERROR "CMake >= 2.8.3 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.8.3...3.23)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_cmake_targets_defined "")
set(_cmake_targets_not_defined "")
set(_cmake_expected_targets "")
foreach(_cmake_expected_target IN ITEMS itkdouble-conversion itksys itkvcl itknetlib itkv3p_netlib itkvnl itkvnl_algo ITKVNLInstantiation ITKCommon itkNetlibSlatec ITKStatistics ITKTransform ITKLabelMap ITKMesh ITKMetaIO ITKSpatialObjects ITKPath ITKQuadEdgeMesh ITKIOImageBase ITKOptimizers ITKPolynomials ITKBiasCorrection ITKFFT ITKTransformFactory ITKIOTransformBase ITKIOTransformInsightLegacy ITKIOTransformMatlab ITKKLMRegionGrowing itklbfgs ITKOptimizersv4 ITKWatersheds)
  list(APPEND _cmake_expected_targets "${_cmake_expected_target}")
  if(TARGET "${_cmake_expected_target}")
    list(APPEND _cmake_targets_defined "${_cmake_expected_target}")
  else()
    list(APPEND _cmake_targets_not_defined "${_cmake_expected_target}")
  endif()
endforeach()
unset(_cmake_expected_target)
if(_cmake_targets_defined STREQUAL _cmake_expected_targets)
  unset(_cmake_targets_defined)
  unset(_cmake_targets_not_defined)
  unset(_cmake_expected_targets)
  unset(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT _cmake_targets_defined STREQUAL "")
  string(REPLACE ";" ", " _cmake_targets_defined_text "${_cmake_targets_defined}")
  string(REPLACE ";" ", " _cmake_targets_not_defined_text "${_cmake_targets_not_defined}")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_cmake_targets_defined_text}\nTargets not yet defined: ${_cmake_targets_not_defined_text}\n")
endif()
unset(_cmake_targets_defined)
unset(_cmake_targets_not_defined)
unset(_cmake_expected_targets)


# Compute the installation prefix relative to this file.
get_filename_component(_IMPORT_PREFIX "${CMAKE_CURRENT_LIST_FILE}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
if(_IMPORT_PREFIX STREQUAL "/")
  set(_IMPORT_PREFIX "")
endif()

# Create imported target itkdouble-conversion
add_library(itkdouble-conversion SHARED IMPORTED)

# Create imported target itksys
add_library(itksys SHARED IMPORTED)

set_target_properties(itksys PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/ITK-4.13"
)

# Create imported target itkvcl
add_library(itkvcl SHARED IMPORTED)

set_target_properties(itkvcl PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/ITK-4.13"
)

# Create imported target itknetlib
add_library(itknetlib SHARED IMPORTED)

set_target_properties(itknetlib PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/ITK-4.13"
)

# Create imported target itkv3p_netlib
add_library(itkv3p_netlib SHARED IMPORTED)

set_target_properties(itkv3p_netlib PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/ITK-4.13"
)

# Create imported target itkvnl
add_library(itkvnl SHARED IMPORTED)

set_target_properties(itkvnl PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/ITK-4.13"
)

# Create imported target itkvnl_algo
add_library(itkvnl_algo SHARED IMPORTED)

set_target_properties(itkvnl_algo PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/ITK-4.13"
)

# Create imported target ITKVNLInstantiation
add_library(ITKVNLInstantiation SHARED IMPORTED)

set_target_properties(ITKVNLInstantiation PROPERTIES
  INTERFACE_LINK_LIBRARIES "itkvnl_algo;itkvnl;itkv3p_netlib;itknetlib;itkvcl;itkvnl_algo;itkvnl;itkv3p_netlib;itknetlib;itkvcl"
)

# Create imported target ITKCommon
add_library(ITKCommon SHARED IMPORTED)

set_target_properties(ITKCommon PROPERTIES
  INTERFACE_LINK_LIBRARIES "itksys;ITKVNLInstantiation"
)

# Create imported target itkNetlibSlatec
add_library(itkNetlibSlatec SHARED IMPORTED)

set_target_properties(itkNetlibSlatec PROPERTIES
  INTERFACE_LINK_LIBRARIES "itkv3p_netlib"
)

# Create imported target ITKStatistics
add_library(ITKStatistics SHARED IMPORTED)

set_target_properties(ITKStatistics PROPERTIES
  INTERFACE_LINK_LIBRARIES "ITKCommon;itkNetlibSlatec"
)

# Create imported target ITKTransform
add_library(ITKTransform SHARED IMPORTED)

set_target_properties(ITKTransform PROPERTIES
  INTERFACE_LINK_LIBRARIES "ITKCommon"
)

# Create imported target ITKLabelMap
add_library(ITKLabelMap SHARED IMPORTED)

# Create imported target ITKMesh
add_library(ITKMesh SHARED IMPORTED)

# Create imported target ITKMetaIO
add_library(ITKMetaIO SHARED IMPORTED)

set_target_properties(ITKMetaIO PROPERTIES
  INTERFACE_LINK_LIBRARIES "C:/build/otb/xdk/lib/zdll.lib;comctl32;wsock32"
)

# Create imported target ITKSpatialObjects
add_library(ITKSpatialObjects SHARED IMPORTED)

set_target_properties(ITKSpatialObjects PROPERTIES
  INTERFACE_LINK_LIBRARIES "ITKTransform"
)

# Create imported target ITKPath
add_library(ITKPath SHARED IMPORTED)

# Create imported target ITKQuadEdgeMesh
add_library(ITKQuadEdgeMesh SHARED IMPORTED)

# Create imported target ITKIOImageBase
add_library(ITKIOImageBase SHARED IMPORTED)

set_target_properties(ITKIOImageBase PROPERTIES
  INTERFACE_LINK_LIBRARIES "ITKCommon"
)

# Create imported target ITKOptimizers
add_library(ITKOptimizers SHARED IMPORTED)

set_target_properties(ITKOptimizers PROPERTIES
  INTERFACE_LINK_LIBRARIES "ITKStatistics"
)

# Create imported target ITKPolynomials
add_library(ITKPolynomials SHARED IMPORTED)

set_target_properties(ITKPolynomials PROPERTIES
  INTERFACE_LINK_LIBRARIES "ITKCommon"
)

# Create imported target ITKBiasCorrection
add_library(ITKBiasCorrection SHARED IMPORTED)

# Create imported target ITKFFT
add_library(ITKFFT SHARED IMPORTED)

set_target_properties(ITKFFT PROPERTIES
  INTERFACE_LINK_LIBRARIES "C:/build/otb/xdk/lib/fftw3.lib;C:/build/otb/xdk/lib/fftw3f.lib"
)

# Create imported target ITKTransformFactory
add_library(ITKTransformFactory SHARED IMPORTED)

set_target_properties(ITKTransformFactory PROPERTIES
  INTERFACE_LINK_LIBRARIES "ITKCommon;ITKTransform"
)

# Create imported target ITKIOTransformBase
add_library(ITKIOTransformBase SHARED IMPORTED)

set_target_properties(ITKIOTransformBase PROPERTIES
  INTERFACE_LINK_LIBRARIES "ITKCommon;ITKTransform;ITKTransformFactory"
)

# Create imported target ITKIOTransformInsightLegacy
add_library(ITKIOTransformInsightLegacy SHARED IMPORTED)

set_target_properties(ITKIOTransformInsightLegacy PROPERTIES
  INTERFACE_LINK_LIBRARIES "ITKIOTransformBase"
)

# Create imported target ITKIOTransformMatlab
add_library(ITKIOTransformMatlab SHARED IMPORTED)

set_target_properties(ITKIOTransformMatlab PROPERTIES
  INTERFACE_LINK_LIBRARIES "ITKIOTransformBase"
)

# Create imported target ITKKLMRegionGrowing
add_library(ITKKLMRegionGrowing SHARED IMPORTED)

set_target_properties(ITKKLMRegionGrowing PROPERTIES
  INTERFACE_LINK_LIBRARIES "ITKCommon"
)

# Create imported target itklbfgs
add_library(itklbfgs SHARED IMPORTED)

# Create imported target ITKOptimizersv4
add_library(ITKOptimizersv4 SHARED IMPORTED)

set_target_properties(ITKOptimizersv4 PROPERTIES
  INTERFACE_LINK_LIBRARIES "ITKOptimizers"
)

# Create imported target ITKWatersheds
add_library(ITKWatersheds SHARED IMPORTED)

set_target_properties(ITKWatersheds PROPERTIES
  INTERFACE_LINK_LIBRARIES "ITKCommon;ITKStatistics;ITKTransform;ITKSpatialObjects;ITKPath;ITKCommon;ITKStatistics;ITKTransform;ITKSpatialObjects;ITKPath;ITKCommon;ITKStatistics;ITKTransform;ITKSpatialObjects;ITKPath;ITKCommon;ITKStatistics;ITKTransform;ITKCommon;ITKStatistics;ITKTransform;ITKSpatialObjects;ITKPath"
)

if(CMAKE_VERSION VERSION_LESS 2.8.12)
  message(FATAL_ERROR "This file relies on consumers using CMake 2.8.12 or greater.")
endif()

# Load information for each installed configuration.
file(GLOB _cmake_config_files "${CMAKE_CURRENT_LIST_DIR}/ITKTargets-*.cmake")
foreach(_cmake_config_file IN LISTS _cmake_config_files)
  include("${_cmake_config_file}")
endforeach()
unset(_cmake_config_file)
unset(_cmake_config_files)

# Cleanup temporary variables.
set(_IMPORT_PREFIX)

# Loop over all imported files and verify that they actually exist
foreach(_cmake_target IN LISTS _cmake_import_check_targets)
  foreach(_cmake_file IN LISTS "_cmake_import_check_files_for_${_cmake_target}")
    if(NOT EXISTS "${_cmake_file}")
      message(FATAL_ERROR "The imported target \"${_cmake_target}\" references the file
   \"${_cmake_file}\"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   \"${CMAKE_CURRENT_LIST_FILE}\"
but not all the files it references.
")
    endif()
  endforeach()
  unset(_cmake_file)
  unset("_cmake_import_check_files_for_${_cmake_target}")
endforeach()
unset(_cmake_target)
unset(_cmake_import_check_targets)

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
